
language: node_js
os:
  - linux
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
script:
  - yarn prepare
  - yarn predeploy
matrix:
  allow_failures: []
  fast_finish: true
branches:
  except:
    - master
    - gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true